import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from './Sidebar/Sidebar'
import TopHeader from './top header/top_header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex flex-row min-h-screen bg-[#FFEEB9] max-[992px]:px-4">
        {/*Left Side Bar */}
        <Sidebar />

        {/*Right Main section*/}
        <div className="w-full max-[992px]:rounded-[25px] rounded-l-[25px] z-0 bg-white h-fit m-7">
          {/*Right TopBar*/}
          <TopHeader />

          {/* OTHER CHILDREN WILL LOAD HERE */}

          <div className="px-6 py-5 md:px-14">{children}</div>
        </div>
      </div>
        
        </body>
    </html>
  )
}
